<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Jocelyn Cramer">

<title>Lab 6: Timeseries Data – Colorado State University Course Webpage</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-9c8f6917bb976eb1370e91c8fae1e261.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="site_libs/htmltools-fill-0.5.9/fill.css" rel="stylesheet">

<script src="site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>

<script src="site_libs/plotly-binding-4.12.0/plotly.js"></script>

<script src="site_libs/typedarray-0.1/typedarray.min.js"></script>

<script src="site_libs/jquery-3.5.1/jquery.min.js"></script>

<link href="site_libs/crosstalk-1.2.2/css/crosstalk.min.css" rel="stylesheet">

<script src="site_libs/crosstalk-1.2.2/js/crosstalk.min.js"></script>

<link href="site_libs/plotly-htmlwidgets-css-2.25.2/plotly-htmlwidgets.css" rel="stylesheet">

<script src="site_libs/plotly-main-2.25.2/plotly-latest.min.js"></script>



<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Colorado State University Course Webpage</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./csu523c_webpage.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./lab-01.html"> 
<span class="menu-text">Lab 1</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./lab-02.html"> 
<span class="menu-text">Lab 2</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./lab-03.html"> 
<span class="menu-text">Lab 3</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./lab-04.html"> 
<span class="menu-text">Lab 4</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./lab-05.html"> 
<span class="menu-text">Lab 5</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./lab-06.html" aria-current="page"> 
<span class="menu-text">Lab 6</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a>
  <ul class="collapse">
  <li><a href="#getting-the-data" id="toc-getting-the-data" class="nav-link" data-scroll-target="#getting-the-data">Getting the Data</a>
  <ul class="collapse">
  <li><a href="#streamflow" id="toc-streamflow" class="nav-link" data-scroll-target="#streamflow">Streamflow</a></li>
  <li><a href="#historic-climate-gridmet" id="toc-historic-climate-gridmet" class="nav-link" data-scroll-target="#historic-climate-gridmet">Historic Climate (GridMET)</a></li>
  <li><a href="#future-climate-maca" id="toc-future-climate-maca" class="nav-link" data-scroll-target="#future-climate-maca">Future Climate (MACA)</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#your-turn" id="toc-your-turn" class="nav-link" data-scroll-target="#your-turn">Your Turn</a>
  <ul class="collapse">
  <li><a href="#convert-to-tsibble" id="toc-convert-to-tsibble" class="nav-link" data-scroll-target="#convert-to-tsibble">1. Convert to tsibble</a></li>
  <li><a href="#plot-the-time-series" id="toc-plot-the-time-series" class="nav-link" data-scroll-target="#plot-the-time-series">2. Plot the Time Series</a></li>
  <li><a href="#seasonal-diagnostics" id="toc-seasonal-diagnostics" class="nav-link" data-scroll-target="#seasonal-diagnostics">3. Seasonal Diagnostics</a></li>
  <li><a href="#stationarity-and-autocorrelation" id="toc-stationarity-and-autocorrelation" class="nav-link" data-scroll-target="#stationarity-and-autocorrelation">4. Stationarity and Autocorrelation</a></li>
  <li><a href="#decomposition" id="toc-decomposition" class="nav-link" data-scroll-target="#decomposition">5. Decomposition</a></li>
  <li><a href="#modeltime-prediction" id="toc-modeltime-prediction" class="nav-link" data-scroll-target="#modeltime-prediction">Modeltime Prediction</a>
  <ul class="collapse">
  <li><a href="#data-preparation" id="toc-data-preparation" class="nav-link" data-scroll-target="#data-preparation">Data Preparation</a></li>
  <li><a href="#train-test-split" id="toc-train-test-split" class="nav-link" data-scroll-target="#train-test-split">Train / Test Split</a></li>
  <li><a href="#model-definition" id="toc-model-definition" class="nav-link" data-scroll-target="#model-definition">Model Definition</a></li>
  <li><a href="#model-fitting" id="toc-model-fitting" class="nav-link" data-scroll-target="#model-fitting">Model Fitting</a></li>
  <li><a href="#calibration-and-accuracy" id="toc-calibration-and-accuracy" class="nav-link" data-scroll-target="#calibration-and-accuracy">Calibration and Accuracy</a></li>
  <li><a href="#test-set-forecast" id="toc-test-set-forecast" class="nav-link" data-scroll-target="#test-set-forecast">Test Set Forecast</a></li>
  <li><a href="#refit-to-full-dataset" id="toc-refit-to-full-dataset" class="nav-link" data-scroll-target="#refit-to-full-dataset">Refit to Full Dataset</a></li>
  <li><a href="#forecast-into-the-future-20242033" id="toc-forecast-into-the-future-20242033" class="nav-link" data-scroll-target="#forecast-into-the-future-20242033">Forecast into the Future (2024–2033)</a></li>
  </ul></li>
  <li><a href="#wrap-up" id="toc-wrap-up" class="nav-link" data-scroll-target="#wrap-up">Wrap-up</a></li>
  <li><a href="#going-further-optional-add-an-upstream-regressor" id="toc-going-further-optional-add-an-upstream-regressor" class="nav-link" data-scroll-target="#going-further-optional-add-an-upstream-regressor">Going Further (Optional): Add an Upstream Regressor</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Lab 6: Timeseries Data</h1>
<p class="subtitle lead">Using Modeltime to predict future streamflow on the Cache la Poudre River</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Jocelyn Cramer </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level1">
<h1>Introduction</h1>
<p>In this lab you will download streamflow data from the Cache la Poudre River (USGS site 06752260) and analyze it using the time series methods introduced in lecture. You will then use <code>modeltime</code> to predict future streamflow using both the time structure of the series and exogenous climate predictors.</p>
<p>This mirrors the Lees Ferry forecasting example from lecture — same <code>dataRetrieval</code> pipeline, same <code>modeltime</code> workflow, but now applied to a river you can see from campus. Like Lees Ferry, the Poudre is an operational water-supply system: Fort Collins, Loveland, and Greeley all depend on it, and the flows you forecast here directly inform how water managers plan deliveries.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidyverse' was built under R version 4.5.3</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plotly)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dataRetrieval)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(climateR)</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(terra)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'terra' was built under R version 4.5.3</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(exactextractr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'exactextractr' was built under R version 4.5.3</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tidymodels' was built under R version 4.5.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'dials' was built under R version 4.5.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'infer' was built under R version 4.5.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'modeldata' was built under R version 4.5.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'parsnip' was built under R version 4.5.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'recipes' was built under R version 4.5.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'rsample' was built under R version 4.5.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tailor' was built under R version 4.5.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tune' was built under R version 4.5.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'workflows' was built under R version 4.5.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'workflowsets' was built under R version 4.5.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'yardstick' was built under R version 4.5.3</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tsibble)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'tsibble' was built under R version 4.5.3</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(feasts)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'feasts' was built under R version 4.5.3</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'fabletools' was built under R version 4.5.3</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(modeltime)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'modeltime' was built under R version 4.5.3</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(timetk)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'timetk' was built under R version 4.5.3</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tseries)   <span class="co"># for stationarity tests</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<section id="getting-the-data" class="level2">
<h2 class="anchored" data-anchor-id="getting-the-data">Getting the Data</h2>
<section id="streamflow" class="level3">
<h3 class="anchored" data-anchor-id="streamflow">Streamflow</h3>
<p>Download daily streamflow for the Poudre at Mouth (USGS 06752260) and aggregate to monthly means. This is the same <code>readNWISdv()</code> + <code>renameNWISColumns()</code> pipeline from Lab 1 — the only addition is <code>yearmonth()</code> from <code>tsibble</code> to create a monthly time index.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>poudre_flow <span class="ot">&lt;-</span> <span class="fu">readNWISdv</span>(</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">siteNumber =</span> <span class="st">"06752260"</span>,</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">parameterCd =</span> <span class="st">"00060"</span>,</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">startDate   =</span> <span class="st">"2013-01-01"</span>,</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">endDate     =</span> <span class="st">"2023-12-31"</span></span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">renameNWISColumns</span>() <span class="sc">|&gt;</span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Date =</span> <span class="fu">yearmonth</span>(Date)) <span class="sc">|&gt;</span></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(Date) <span class="sc">|&gt;</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Flow =</span> <span class="fu">mean</span>(Flow))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="historic-climate-gridmet" class="level3">
<h3 class="anchored" data-anchor-id="historic-climate-gridmet">Historic Climate (GridMET)</h3>
<p>We will use <code>climateR::getTerraClim()</code> to download monthly climate data for the Poudre basin (max temperature, precipitation, solar radiation). The <code>exactextractr</code> package spatially averages each raster layer over the basin polygon.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>basin <span class="ot">&lt;-</span> <span class="fu">findNLDI</span>(<span class="at">nwis =</span> <span class="st">"06752260"</span>, <span class="at">find =</span> <span class="st">"basin"</span>)</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>sdate <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="st">"2013-01-01"</span>)</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>edate <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="st">"2023-12-31"</span>)</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>gm <span class="ot">&lt;-</span> <span class="fu">getTerraClim</span>(</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">AOI       =</span> basin<span class="sc">$</span>basin,</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">var       =</span> <span class="fu">c</span>(<span class="st">"tmax"</span>, <span class="st">"ppt"</span>, <span class="st">"srad"</span>),</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">startDate =</span> sdate,</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">endDate   =</span> edate</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unlist</span>() <span class="sc">|&gt;</span></span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rast</span>() <span class="sc">|&gt;</span></span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">exact_extract</span>(basin<span class="sc">$</span>basin, <span class="st">"mean"</span>, <span class="at">progress =</span> <span class="cn">FALSE</span>)</span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a>historic <span class="ot">&lt;-</span> <span class="fu">mutate</span>(gm, <span class="at">id =</span> <span class="st">"gridmet"</span>) <span class="sc">|&gt;</span></span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="sc">-</span>id) <span class="sc">|&gt;</span></span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">name =</span> <span class="fu">sub</span>(<span class="st">"^mean</span><span class="sc">\\</span><span class="st">."</span>, <span class="st">""</span>, name)) <span class="sc">|&gt;</span></span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">extract</span>(name, <span class="at">into =</span> <span class="fu">c</span>(<span class="st">"var"</span>, <span class="st">"index"</span>), <span class="st">"(.*)_([^_]+$)"</span>) <span class="sc">|&gt;</span></span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">index =</span> <span class="fu">as.integer</span>(index)) <span class="sc">|&gt;</span></span>
<span id="cb31-21"><a href="#cb31-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Date =</span> <span class="fu">yearmonth</span>(<span class="fu">seq.Date</span>(sdate, edate, <span class="at">by =</span> <span class="st">"month"</span>)[<span class="fu">as.numeric</span>(index)])) <span class="sc">|&gt;</span></span>
<span id="cb31-22"><a href="#cb31-22" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">id_cols =</span> Date, <span class="at">names_from =</span> var, <span class="at">values_from =</span> value) <span class="sc">|&gt;</span></span>
<span id="cb31-23"><a href="#cb31-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">right_join</span>(poudre_flow, <span class="at">by =</span> <span class="st">"Date"</span>)</span>
<span id="cb31-24"><a href="#cb31-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb31-25"><a href="#cb31-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Validate: should have 132 rows (11 years × 12 months). If fewer, climate data</span></span>
<span id="cb31-26"><a href="#cb31-26" aria-hidden="true" tabindex="-1"></a><span class="co"># is missing for some months and those flow months were silently dropped.</span></span>
<span id="cb31-27"><a href="#cb31-27" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="st">"Climate join dropped flow months — check GridMET download"</span> <span class="ot">=</span> <span class="fu">nrow</span>(historic) <span class="sc">==</span> <span class="dv">132</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="future-climate-maca" class="level3">
<h3 class="anchored" data-anchor-id="future-climate-maca">Future Climate (MACA)</h3>
<p>Any time exogenous predictors are used for forecasting, <strong>future values of those predictors must also be available</strong>. We use MACA — a statistically downscaled climate dataset developed by the same group as GridMET — to get projected temperature, precipitation, and solar radiation through 2033.</p>
<p>Two differences from GridMET: temperature is in Kelvin (subtract 273.15 for °C) and variable names differ slightly.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>sdate <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="st">"2024-01-01"</span>)</span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a>edate <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(<span class="st">"2033-12-31"</span>)</span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a>maca <span class="ot">&lt;-</span> <span class="fu">getMACA</span>(</span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">AOI      =</span> basin<span class="sc">$</span>basin,</span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">var      =</span> <span class="fu">c</span>(<span class="st">"tasmax"</span>, <span class="st">"pr"</span>, <span class="st">"rsds"</span>),</span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">timeRes  =</span> <span class="st">"month"</span>,</span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">startDate =</span> sdate,</span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">endDate   =</span> edate</span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">unlist</span>() <span class="sc">|&gt;</span></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rast</span>() <span class="sc">|&gt;</span></span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">exact_extract</span>(basin<span class="sc">$</span>basin, <span class="st">"mean"</span>, <span class="at">progress =</span> <span class="cn">FALSE</span>)</span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-15"><a href="#cb32-15" aria-hidden="true" tabindex="-1"></a>future <span class="ot">&lt;-</span> <span class="fu">mutate</span>(maca, <span class="at">id =</span> <span class="st">"maca"</span>) <span class="sc">|&gt;</span></span>
<span id="cb32-16"><a href="#cb32-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_longer</span>(<span class="at">cols =</span> <span class="sc">-</span>id) <span class="sc">|&gt;</span></span>
<span id="cb32-17"><a href="#cb32-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">name =</span> <span class="fu">sub</span>(<span class="st">"^mean</span><span class="sc">\\</span><span class="st">."</span>, <span class="st">""</span>, name)) <span class="sc">|&gt;</span></span>
<span id="cb32-18"><a href="#cb32-18" aria-hidden="true" tabindex="-1"></a>  tidyr<span class="sc">::</span><span class="fu">extract</span>(name, <span class="at">into =</span> <span class="fu">c</span>(<span class="st">"var"</span>, <span class="st">"index"</span>), <span class="st">"(.*)_([^_]+$)"</span>) <span class="sc">|&gt;</span></span>
<span id="cb32-19"><a href="#cb32-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">index =</span> <span class="fu">as.integer</span>(index)) <span class="sc">|&gt;</span></span>
<span id="cb32-20"><a href="#cb32-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">Date =</span> <span class="fu">yearmonth</span>(<span class="fu">seq.Date</span>(sdate, edate, <span class="at">by =</span> <span class="st">"month"</span>)[<span class="fu">as.numeric</span>(index)])) <span class="sc">|&gt;</span></span>
<span id="cb32-21"><a href="#cb32-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">id_cols =</span> Date, <span class="at">names_from =</span> var, <span class="at">values_from =</span> value)</span>
<span id="cb32-22"><a href="#cb32-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-23"><a href="#cb32-23" aria-hidden="true" tabindex="-1"></a><span class="co"># Rename the 3 climate columns to match GridMET names (Date column stays first)</span></span>
<span id="cb32-24"><a href="#cb32-24" aria-hidden="true" tabindex="-1"></a><span class="fu">stopifnot</span>(<span class="st">"Unexpected MACA column count"</span> <span class="ot">=</span> <span class="fu">ncol</span>(future) <span class="sc">==</span> <span class="dv">4</span>)</span>
<span id="cb32-25"><a href="#cb32-25" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(future)[<span class="dv">2</span><span class="sc">:</span><span class="dv">4</span>] <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"ppt"</span>, <span class="st">"srad"</span>, <span class="st">"tmax"</span>)  <span class="co"># order matches getMACA var request</span></span>
<span id="cb32-26"><a href="#cb32-26" aria-hidden="true" tabindex="-1"></a>future <span class="ot">&lt;-</span> <span class="fu">mutate</span>(future, <span class="at">tmax =</span> tmax <span class="sc">-</span> <span class="fl">273.15</span>)   <span class="co"># Kelvin → °C</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<hr>
</section>
</section>
</section>
<section id="your-turn" class="level1">
<h1>Your Turn</h1>
<section id="convert-to-tsibble" class="level2">
<h2 class="anchored" data-anchor-id="convert-to-tsibble">1. Convert to tsibble</h2>
<p>Convert <code>historic</code> to a <code>tsibble</code> object using <code>as_tsibble()</code>. A <code>tsibble</code> is a tidy time series data frame — it retains the date index and integrates with <code>feasts</code> functions for decomposition and visualization. Think of it as a tibble that knows it is ordered in time.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>Poudre <span class="ot">&lt;-</span> <span class="fu">as_tsibble</span>(historic, <span class="at">index =</span> Date)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="plot-the-time-series" class="level2">
<h2 class="anchored" data-anchor-id="plot-the-time-series">2. Plot the Time Series</h2>
<p>Use <code>ggplot</code> to plot monthly Flow over time. Use <code>plot_ly()</code> from <code>plotly</code> for an interactive version — this lets you zoom into specific years or hover over values.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>Plot_1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(Poudre, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">as.Date</span>(Date), <span class="at">y =</span> Flow)) <span class="sc">+</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"turquoise3"</span>) <span class="sc">+</span></span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Cache la Poudre Monthly Streamflow"</span>, <span class="at">y =</span> <span class="st">"Flow (cfs)"</span>, <span class="at">x =</span> <span class="cn">NULL</span>) <span class="sc">+</span></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>Plot_1</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lab-06_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot_ly</span>(Poudre, <span class="at">x =</span> <span class="sc">~</span><span class="fu">as.Date</span>(Date), <span class="at">y =</span> <span class="sc">~</span>Flow, <span class="at">type =</span> <span class="st">"scatter"</span>, <span class="at">mode =</span> <span class="st">"lines"</span>, </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">line =</span> <span class="fu">list</span>(<span class="at">color =</span> <span class="st">"maroon"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">layout</span>(<span class="at">title =</span> <span class="st">"Cache la Poudre Monthly Streamflow (Interactive)"</span>, <span class="at">xaxis =</span> <span class="fu">list</span>(<span class="at">title =</span> <span class="st">"Date"</span>),</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">yaxis =</span> <span class="fu">list</span>(<span class="at">title =</span> <span class="st">"Flow (cfs)"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div class="plotly html-widget html-fill-item" id="htmlwidget-d1c148947a43703c0e71" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-d1c148947a43703c0e71">{"x":{"visdat":{"7514231810c4":["function () ","plotlyVisDat"]},"cur_data":"7514231810c4","attrs":{"7514231810c4":{"x":{},"y":{},"mode":"lines","line":{"color":"maroon"},"alpha_stroke":1,"sizes":[10,100],"spans":[1,20],"type":"scatter"}},"layout":{"margin":{"b":40,"l":60,"t":25,"r":10},"title":"Cache la Poudre Monthly Streamflow (Interactive)","xaxis":{"domain":[0,1],"automargin":true,"title":"Date"},"yaxis":{"domain":[0,1],"automargin":true,"title":"Flow (cfs)"},"hovermode":"closest","showlegend":false},"source":"A","config":{"modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"data":[{"x":["2013-01-01","2013-02-01","2013-03-01","2013-04-01","2013-05-01","2013-06-01","2013-07-01","2013-08-01","2013-09-01","2013-10-01","2013-11-01","2013-12-01","2014-01-01","2014-02-01","2014-03-01","2014-04-01","2014-05-01","2014-06-01","2014-07-01","2014-08-01","2014-09-01","2014-10-01","2014-11-01","2014-12-01","2015-01-01","2015-02-01","2015-03-01","2015-04-01","2015-05-01","2015-06-01","2015-07-01","2015-08-01","2015-09-01","2015-10-01","2015-11-01","2015-12-01","2016-01-01","2016-02-01","2016-03-01","2016-04-01","2016-05-01","2016-06-01","2016-07-01","2016-08-01","2016-09-01","2016-10-01","2016-11-01","2016-12-01","2017-01-01","2017-02-01","2017-03-01","2017-04-01","2017-05-01","2017-06-01","2017-07-01","2017-08-01","2017-09-01","2017-10-01","2017-11-01","2017-12-01","2018-01-01","2018-02-01","2018-03-01","2018-04-01","2018-05-01","2018-06-01","2018-07-01","2018-08-01","2018-09-01","2018-10-01","2018-11-01","2018-12-01","2019-01-01","2019-02-01","2019-03-01","2019-04-01","2019-05-01","2019-06-01","2019-07-01","2019-08-01","2019-09-01","2019-10-01","2019-11-01","2019-12-01","2020-01-01","2020-02-01","2020-03-01","2020-04-01","2020-05-01","2020-06-01","2020-07-01","2020-08-01","2020-09-01","2020-10-01","2020-11-01","2020-12-01","2021-01-01","2021-02-01","2021-03-01","2021-04-01","2021-05-01","2021-06-01","2021-07-01","2021-08-01","2021-09-01","2021-10-01","2021-11-01","2021-12-01","2022-01-01","2022-02-01","2022-03-01","2022-04-01","2022-05-01","2022-06-01","2022-07-01","2022-08-01","2022-09-01","2022-10-01","2022-11-01","2022-12-01","2023-01-01","2023-02-01","2023-03-01","2023-04-01","2023-05-01","2023-06-01","2023-07-01","2023-08-01","2023-09-01","2023-10-01","2023-11-01","2023-12-01"],"y":[18.125806451612902,18.046428571428571,8.2087096774193551,5.940666666666667,332.57967741935482,299.98933333333332,75.561290322580646,48.819354838709678,1085.3533333333332,146.09999999999999,162.76666666666668,124.43870967741935,91.264516129032259,94.285714285714292,144.04838709677421,190.42666666666668,1425.3225806451612,1916.5,260.60322580645163,177.53548387096774,87.963333333333338,121.2,146.97333333333333,114.79032258064517,114.29032258064517,104.625,144.97419354838709,265.67666666666668,1926.4516129032259,2304.9666666666667,315.25806451612902,144.06129032258065,60.771333333333331,39.670967741935485,53.990000000000002,94.41935483870968,76.522580645161284,101.97586206896551,96.774193548387103,489.26666666666665,1619.8064516129032,1249.9000000000001,153.68709677419355,133.68064516129033,73.074333333333328,44.073870967741932,13.68,11.942258064516128,72.432258064516134,67.517857142857139,27.807741935483872,21.762666666666668,902.14193548387095,1109.0999999999999,156.19032258064516,282.45161290322579,240.07333333333332,117.02580645161291,61.856666666666669,79.5741935483871,57.819354838709678,22.503214285714286,33.960645161290323,23.817666666666668,778.12903225806451,388.25333333333333,125.21612903225807,84.035483870967738,46.863333333333337,130.30000000000001,15.268000000000001,10.212903225806452,12.558709677419355,29.060714285714287,43.183870967741939,41.073333333333331,236.53548387096774,743.5333333333333,339.67741935483872,151.63870967741934,59.546666666666667,82.338709677419359,7.5010000000000003,39.806129032258063,25.961290322580645,16.967586206896552,12.301612903225807,25.099,234.41580645161289,433.41000000000003,101.01290322580645,66.406451612903226,31.838666666666668,93.033225806451611,9.6799999999999997,31.087096774193547,22.323870967741936,31.449999999999999,22.644193548387097,27.753333333333334,1227.8709677419354,657.83333333333337,111.7741935483871,76.213548387096779,11.582666666666666,25.545161290322582,37.219999999999999,40.848387096774196,57.806451612903224,55.36785714285714,14.366129032258065,35.910333333333334,262.72161290322583,510.75999999999999,102.59354838709677,59.882580645161291,18.518333333333334,69.109354838709677,11.209999999999999,10.371612903225806,7.2919354838709678,21.900357142857143,28.806451612903228,76.760000000000005,648.5,1499.2333333333333,187.67451612903227,91.032258064516128,37.510333333333335,73.877741935483868,17.914999999999999,13.609677419354838],"mode":"lines","line":{"color":"maroon"},"type":"scatter","marker":{"color":"rgba(31,119,180,1)","line":{"color":"rgba(31,119,180,1)"}},"error_y":{"color":"rgba(31,119,180,1)"},"error_x":{"color":"rgba(31,119,180,1)"},"xaxis":"x","yaxis":"y","frame":null}],"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
</section>
<section id="seasonal-diagnostics" class="level2">
<h2 class="anchored" data-anchor-id="seasonal-diagnostics">3. Seasonal Diagnostics</h2>
<p>Before fitting any model, inspect the seasonal structure using two complementary <code>feasts</code> plots.</p>
<p><strong>Subseries plot</strong> — one panel per month, each line is one year, the blue line is the monthly mean across all years:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gg_subseries</span>(Poudre, <span class="at">y =</span> Flow) <span class="sc">+</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Cache la Poudre Flow Patterns"</span>, <span class="at">y =</span> <span class="st">"Flow (cfs)"</span>, <span class="at">x =</span> <span class="st">"Year"</span>) <span class="sc">+</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">2</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `gg_subseries()` was deprecated in feasts 0.4.2.
ℹ Please use `ggtime::gg_subseries()` instead.
ℹ Graphics functions have been moved to the {ggtime} package. Please use
  `library(ggtime)` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lab-06_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Seasonal plot</strong> — each line is one year plotted over the calendar cycle. Parallel lines = stable seasonal shape; diverging lines = changing pattern:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">gg_season</span>(Poudre, <span class="at">y =</span> Flow) <span class="sc">+</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Cache la Poudre Seasonal Flow Shape"</span>, <span class="at">y =</span> <span class="st">"Flow (cfs)"</span>, <span class="at">x =</span> <span class="st">"Month"</span>) <span class="sc">+</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `gg_season()` was deprecated in feasts 0.4.2.
ℹ Please use `ggtime::gg_season()` instead.
ℹ Graphics functions have been moved to the {ggtime} package. Please use
  `library(ggtime)` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lab-06_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Describe what you see. How are “seasons” defined in these plots? Is the seasonal shape consistent across years, or does it change? What physical process drives the May–June peak?</p>
<blockquote class="blockquote">
<p>The period between May and June in both plots shows significantly higher flows (cfs) compared to the rest of the year, represented as baseflow conditions. There is also a noticeable spike in September 2013, likely caused by a major rainfall or late-season snowfall event. Seasons are defined by monthly variability patterns in stream discharge throughout the year. Overall, the hydrographs display a characteristic seasonal pattern common in western snowmelt-driven rivers, where streamflow increases sharply during late spring and early summer as mountain snowpack melts (Stewart et al.&nbsp;2005). Although the magnitude of flow varies considerably between years, the timing of peak discharge remains consistent. This indicates that the watershed is strongly influenced by snowfall accumulation and snowmelt as the dominant form of precipitation input. Because this region is located in the Rocky Mountains, it is expected that the Cache la Poudre River would follow trends typical of snowmelt-dominated mountain watersheds (Barnett et al.&nbsp;2005).</p>
</blockquote>
<ul>
<li><p>Barnett et al.&nbsp;(2005). Potential impacts of a warming climate on water availability in snow-dominated regions. Nature, 438(7066), 303–309. https://doi.org/10.1038/nature04141.</p></li>
<li><p>Stewart et al.&nbsp;(2005). Changes toward earlier streamflow timing across western North America. U.S. Geological Survey. https://pubs.usgs.gov/fs/2005/3018/pdf/FS2005_3018.pdf.</p></li>
</ul>
</section>
<section id="stationarity-and-autocorrelation" class="level2">
<h2 class="anchored" data-anchor-id="stationarity-and-autocorrelation">4. Stationarity and Autocorrelation</h2>
<p>Two diagnostics that directly inform ARIMA model selection:</p>
<p><strong>Lag plot</strong> — plots Flow against its own lagged values. Strong linear patterns = high autocorrelation (ARIMA has something to work with). A diffuse cloud = no memory. Use <code>log1p(Flow)</code> — on the raw scale, peak months compress all other observations into the corner and hide the structure.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>Poudre <span class="sc">|&gt;</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">log_flow =</span> <span class="fu">log1p</span>(Flow)) <span class="sc">|&gt;</span></span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">gg_lag</span>(<span class="at">y =</span> log_flow, <span class="at">geom =</span> <span class="st">"point"</span>) <span class="sc">+</span></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Cache la Poudre Lag Flow Structure"</span>, <span class="at">x =</span> <span class="st">"Lag"</span>, <span class="at">y =</span> <span class="st">"Flow"</span>) <span class="sc">+</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `gg_lag()` was deprecated in feasts 0.4.2.
ℹ Please use `ggtime::gg_lag()` instead.
ℹ Graphics functions have been moved to the {ggtime} package. Please use
  `library(ggtime)` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lab-06_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>Stationarity tests</strong> — ARIMA requires a stationary series (constant mean and variance). Test formally before fitting:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Test on log_flow — that's what ARIMA will actually model</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>log_flow_vec <span class="ot">&lt;-</span> <span class="fu">log1p</span>(Poudre<span class="sc">$</span>Flow)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="co"># ADF: H0 = non-stationary; p &lt; 0.05 rejects non-stationarity → series IS stationary</span></span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a><span class="fu">adf.test</span>(log_flow_vec)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in adf.test(log_flow_vec): p-value smaller than printed p-value</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Augmented Dickey-Fuller Test

data:  log_flow_vec
Dickey-Fuller = -7.3292, Lag order = 5, p-value = 0.01
alternative hypothesis: stationary</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># KPSS: H0 = stationary; p &lt; 0.05 rejects stationarity → series is NOT stationary</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a><span class="fu">kpss.test</span>(log_flow_vec)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    KPSS Test for Level Stationarity

data:  log_flow_vec
KPSS Level = 0.50753, Truncation lag parameter = 4, p-value = 0.03997</code></pre>
</div>
</div>
<p>What do the tests tell you? If the series is non-stationary, ARIMA will need <code>d ≥ 1</code> (differencing). Does the lag plot support the same conclusion?</p>
<blockquote class="blockquote">
<p>The Augmented Dickey-Fuller (ADF) test revealed a Dickey-Fuller statistic of -7.3292, a lag order of 5, and a p-value of 0.01. This suggests the log-transformed flow series is stationary because the result is statistically significant. In contrast, the KPSS Test for Level Stationarity revealed a KPSS level of 0.50753, a truncation lag parameter of 4, and a p-value of 0.03997. This test was also significant, but it suggests the flow series is non-stationary, which contradicts the ADF test. Due to the remaining seasonal structure in the river flow data, the series is not completely stationary and requires a differencing term (d ≥ 1). The lag plots further support this conclusion by showing clear clustering patterns by season.</p>
</blockquote>
</section>
<section id="decomposition" class="level2">
<h2 class="anchored" data-anchor-id="decomposition">5. Decomposition</h2>
<p>Use <code>model(STL(...))</code> to decompose the time series into trend, seasonality, and remainder. Choose a trend window size you feel is appropriate and justify your choice. Extract components with <code>components()</code> and visualize with <code>autoplot()</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a>Decomposition <span class="ot">&lt;-</span> Poudre <span class="sc">|&gt;</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">model</span>(<span class="fu">STL</span>(Flow <span class="sc">~</span> <span class="fu">trend</span>(<span class="at">window =</span> <span class="dv">12</span>) <span class="sc">+</span> <span class="fu">season</span>(<span class="at">window =</span> <span class="st">"periodic"</span>))) <span class="sc">|&gt;</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">components</span>()</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(Decomposition)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: `autoplot.dcmp_ts()` was deprecated in fabletools 0.6.0.
ℹ Please use `ggtime::autoplot.dcmp_ts()` instead.
ℹ Graphics functions have been moved to the {ggtime} package. Please use
  `library(ggtime)` instead.</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lab-06_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Describe what you see:</p>
<ul>
<li>What does the <strong>trend</strong> tell you about long-term changes in Poudre flow? Is there evidence of a decline consistent with climate change or upstream demand?</li>
<li>What drives the <strong>seasonal</strong> component? (Hint: snowmelt, irrigation withdrawals, reservoir releases)</li>
<li>Are there any spikes in the <strong>remainder</strong> that correspond to anomalous years you can identify?</li>
</ul>
<blockquote class="blockquote">
<p>The trend line indicating changes in the Cache la Poudre River over the last 10 years shows clear seasonal differences in streamflow. Although the data indicates a significant difference in flow between 2013–2016 and 2016–2024, the earlier period likely reflects wetter conditions and above-average snowpack in northern Colorado during those years. This does not mean long-term trends are not declining, but the magnitude of decline is less pronounced because the earlier years were unusually wet. Therefore, there is still evidence suggesting climate-related declines in flow, although a longer dataset would provide a more reliable long-term average. The seasonal component is primarily driven by mountain snowmelt, which is characteristic of Rocky Mountain hydrology (Barnett et al.&nbsp;2005). The Cache la Poudre River experiences strong spring runoff pulses from melting snowpack, followed by lower flows during late summer and fall when irrigation demand increases and reservoir operations regulate streamflow (Cache n.d.). The remainder component highlights anomalous flow events cannot be completely visualized in the seasonal or trend sections. The largest anomalies occur between 2013–2016, corresponding to wetter years and high runoff conditions, while 2023 also appears as an above-average flow year relative to the surrounding period.</p>
</blockquote>
<ul>
<li><p>Cache la Poudre River National Heritage Area. (n.d.). Water storage. https://poudreheritage.org/water-storage/.</p></li>
<li><p>Barnett et al.&nbsp;(2005). Potential impacts of a warming climate on water availability in snow-dominated regions. Nature, 438(7066), 303–309. https://doi.org/10.1038/nature04141.</p></li>
<li><p>National Oceanic and Atmospheric Administration (NOAA) (2014). Monthly climate report for North America: December 2014. National Centers for Environmental Information. https://www.ncei.noaa.gov/access/monitoring/monthly-report/snow/201413.</p></li>
</ul>
<hr>
</section>
<section id="modeltime-prediction" class="level2">
<h2 class="anchored" data-anchor-id="modeltime-prediction">Modeltime Prediction</h2>
<section id="data-preparation" class="level3">
<h3 class="anchored" data-anchor-id="data-preparation">Data Preparation</h3>
<p>Convert the historic tsibble and future tibble to plain tibbles with a <code>Date</code> column for <code>modeltime</code>. All predictor columns must be present in both the historic and future datasets — this is what enables the 10-year climate-driven forecast.</p>
<p>Streamflow is strictly non-negative but right-skewed — snowmelt peaks dwarf base-flow months. To prevent models from predicting negative flows, add a <strong>log-transformed response</strong> with <code>log1p(Flow)</code> (<code>log(Flow + 1)</code>, safe when flow is near zero). Fit all models on <code>log_flow</code>; back-transform predictions with <code>expm1()</code> (= <code>exp(x) - 1</code>) to return to cfs units.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>Poudre_Table <span class="ot">&lt;-</span> Poudre <span class="sc">|&gt;</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">|&gt;</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">date =</span> <span class="fu">as.Date</span>(Date), <span class="at">log_flow =</span> <span class="fu">log1p</span>(Flow)) <span class="sc">|&gt;</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(date, log_flow, Flow, ppt, srad, tmax)</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>Future_Table <span class="ot">&lt;-</span> future <span class="sc">|&gt;</span></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">|&gt;</span></span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">date =</span> <span class="fu">as.Date</span>(Date)) <span class="sc">|&gt;</span></span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(date, ppt, srad, tmax)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="train-test-split" class="level3">
<h3 class="anchored" data-anchor-id="train-test-split">Train / Test Split</h3>
<p>Hold out the last 24 months (2022–2023) as the test set. This mirrors the <code>assess = "60 months"</code> logic from the CO₂ and Lees Ferry examples — the test set is always the most recent data, never a random sample.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Note: time_series_split() is deterministic — it always cuts at the same point</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="co"># regardless of the seed. set.seed() is kept here as a tidymodels convention</span></span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a><span class="co"># (some resampling functions are random), but removing it gives identical results.</span></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">10291991</span>)</span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>splits <span class="ot">&lt;-</span> <span class="fu">time_series_split</span>(Poudre_Table, <span class="at">assess =</span> <span class="st">"24 months"</span>, <span class="at">cumulative =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Using date_var: date</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>training <span class="ot">&lt;-</span> <span class="fu">training</span>(splits)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>testing  <span class="ot">&lt;-</span> <span class="fu">testing</span>(splits)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="model-definition" class="level3">
<h3 class="anchored" data-anchor-id="model-definition">Model Definition</h3>
<p>Choose at least three models — one ARIMA and one Prophet are required. Store model specifications in a list:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a>Models <span class="ot">&lt;-</span> <span class="fu">list</span>(</span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>  <span class="co"># ARIMA + XGBoost residual boosting — picks up nonlinear climate relationships</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arima_boost</span>() <span class="sc">|&gt;</span> <span class="fu">set_engine</span>(<span class="st">"auto_arima_xgboost"</span>),</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Prophet — handles trend breaks, missing data, and multiple seasonalities</span></span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">prophet_reg</span>() <span class="sc">|&gt;</span> <span class="fu">set_engine</span>(<span class="st">"prophet"</span>),</span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Exponential smoothing — strong baseline for multiplicative seasonal data </span></span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">exp_smoothing</span>() <span class="sc">|&gt;</span> <span class="fu">set_engine</span>(<span class="st">"ets"</span>)</span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="model-fitting" class="level3">
<h3 class="anchored" data-anchor-id="model-fitting">Model Fitting</h3>
<p>Fit all models to the training data on the log scale. Exclude the raw <code>Flow</code> column so models only see <code>log_flow</code> as the response — each engine handles <code>date</code> and climate predictors internally.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>Models_2 <span class="ot">&lt;-</span> <span class="fu">map</span>(Models, <span class="sc">~</span> <span class="fu">fit</span>(.x, log_flow <span class="sc">~</span> ., <span class="at">data =</span> <span class="fu">select</span>(training, <span class="sc">-</span>Flow)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>frequency = 12 observations per 1 year</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Disabling weekly seasonality. Run prophet with weekly.seasonality=TRUE to override this.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Disabling daily seasonality. Run prophet with daily.seasonality=TRUE to override this.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>frequency = 12 observations per 1 year</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>(Models_Table <span class="ot">&lt;-</span> <span class="fu">as_modeltime_table</span>(Models_2))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># Modeltime Table
# A tibble: 3 × 3
  .model_id .model   .model_desc                              
      &lt;int&gt; &lt;list&gt;   &lt;chr&gt;                                    
1         1 &lt;fit[+]&gt; ARIMA(1,0,1)(0,1,1)[12] W/ XGBOOST ERRORS
2         2 &lt;fit[+]&gt; PROPHET W/ REGRESSORS                    
3         3 &lt;fit[+]&gt; ETS(A,N,A)                               </code></pre>
</div>
</div>
</section>
<section id="calibration-and-accuracy" class="level3">
<h3 class="anchored" data-anchor-id="calibration-and-accuracy">Calibration and Accuracy</h3>
<p>Calibrate on the test set (2022–2023) to compute out-of-sample accuracy metrics. Pass <code>select(testing, -Flow)</code> so calibration uses the log-scale response:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>calibration_table <span class="ot">&lt;-</span> <span class="fu">modeltime_calibrate</span>(Models_Table, <span class="at">new_data =</span> <span class="fu">select</span>(testing, <span class="sc">-</span>Flow), <span class="at">quiet =</span> <span class="cn">FALSE</span>)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a><span class="fu">modeltime_accuracy</span>(calibration_table) <span class="sc">|&gt;</span></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(mae) <span class="sc">|&gt;</span></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(.model_desc, mae, mape, mase, rmse, rsq)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 6
  .model_desc                                 mae  mape  mase  rmse   rsq
  &lt;chr&gt;                                     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 ETS(A,N,A)                                0.511  15.7 0.518 0.621 0.820
2 ARIMA(1,0,1)(0,1,1)[12] W/ XGBOOST ERRORS 0.562  17.7 0.569 0.720 0.730
3 PROPHET W/ REGRESSORS                     0.580  16.0 0.588 0.691 0.783</code></pre>
</div>
</div>
<p>Describe what you see. Use these benchmarks to interpret the numbers:</p>
<ul>
<li><strong>MASE &lt; 1</strong> — the model beats a naïve seasonal forecast (last year’s same month)</li>
<li><strong>MAPE</strong> — intuitive % error, but inflated in low-flow months when Flow ≈ 0</li>
<li><strong>RMSE</strong> — penalizes large errors heavily; compare to mean test-period flow for context</li>
<li>Do boosted models (ARIMA-boost, Prophet-boost) outperform their base versions? If so, the nonlinear climate signal is worth capturing.</li>
</ul>
<blockquote class="blockquote">
<p>Evaluation of the three modeling methods (ETS[A,N,A], ARIMA, and Prophet with regressors) revealed that the ETS(A,N,A) model performed the best overall. This model had the lowest MAE (0.5107), MASE (0.5177), and RMSE (0.6212), while also producing the highest r-squared value (0.8198). Although ETS performed best, the differences between models were relatively small, as the lowest r-squared value was still fairly high at 0.783. Because all MASE values were below 1, each model outperformed a naïve seasonal forecast. MAPE values were also similar across models (15–18%), indicating relatively low forecasting error. RMSE values were similarly low and close between models, suggesting that all models were able to capture changes in streamflow (cfs) well. Overall, the boosted models (ARIMA and Prophet with regressors) did not outperform the simpler ETS model. This suggests that the ETS method was just as effective at capturing the seasonal variability in streamflow as the more complex boosted approaches.</p>
</blockquote>
</section>
<section id="test-set-forecast" class="level3">
<h3 class="anchored" data-anchor-id="test-set-forecast">Test Set Forecast</h3>
<p>Forecast over the held-out test period and compare predictions to actuals. Back-transform with <code>expm1()</code> to return predictions to cfs. Two details matter: (1) <code>expm1(x)</code> is the exact inverse of <code>log1p(x)</code> and always returns values ≥ 0; (2) confidence interval lower bounds on the log scale can be slightly negative — floor them at 0 with <code>pmax(.conf_lo, 0)</code> <em>before</em> back-transforming so the ribbon never dips below zero cfs:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a>test_forecast <span class="ot">&lt;-</span> calibration_table <span class="sc">|&gt;</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">modeltime_forecast</span>(<span class="at">new_data =</span> <span class="fu">select</span>(testing, <span class="sc">-</span>Flow), <span class="at">actual_data =</span> Poudre_Table) <span class="sc">|&gt;</span></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">.value   =</span> <span class="fu">expm1</span>(.value), <span class="at">.conf_lo =</span> <span class="fu">expm1</span>(<span class="fu">pmax</span>(.conf_lo, <span class="dv">0</span>)), <span class="at">.conf_hi =</span> <span class="fu">expm1</span>(.conf_hi))</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>test_forecast <span class="sc">|&gt;</span></span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(.key <span class="sc">==</span> <span class="st">"actual"</span>) <span class="sc">|&gt;</span></span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> .index, <span class="at">y =</span> .value)) <span class="sc">+</span></span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"grey40"</span>) <span class="sc">+</span></span>
<span id="cb63-9"><a href="#cb63-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> <span class="fu">filter</span>(test_forecast, .key <span class="sc">==</span> <span class="st">"prediction"</span>), <span class="fu">aes</span>(<span class="at">color =</span> .model_desc)) <span class="sc">+</span></span>
<span id="cb63-10"><a href="#cb63-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">data =</span> <span class="fu">filter</span>(test_forecast, .key <span class="sc">==</span> <span class="st">"prediction"</span>),</span>
<span id="cb63-11"><a href="#cb63-11" aria-hidden="true" tabindex="-1"></a>              <span class="fu">aes</span>(<span class="at">ymin =</span> .conf_lo, <span class="at">ymax =</span> .conf_hi, <span class="at">fill =</span> .model_desc), <span class="at">alpha =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb63-12"><a href="#cb63-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Cache la Poudre Test Set Forecast vs Observed"</span>, <span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Flow (cfs)"</span>, <span class="at">color =</span> <span class="st">"Model"</span>,</span>
<span id="cb63-13"><a href="#cb63-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Model"</span>) <span class="sc">+</span></span>
<span id="cb63-14"><a href="#cb63-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb63-15"><a href="#cb63-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lab-06_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Do predictions track actuals during the 2022–2023 test window? Are confidence intervals capturing observed values? Note any discontinuities at the 2022 boundary between training and test.</p>
<blockquote class="blockquote">
<p>The predictions from the models somewhat track the actual values during the test window (2022–2023). They clearly capture the timing of seasonal peaks, particularly during spring snowmelt. However, the models vary in their ability to capture peak flow magnitudes. All models perform reasonably well in 2022, but they underestimate the larger peak flows observed in 2023. The ETS(A,N,A) model follows the observed flow most closely in 2022, with a slight overestimation, whereas the ARIMA model slightly underestimates flow in 2023 but remains the closest to the observed peak. The confidence intervals generally capture the observed values, especially during periods of low flow. However, the ARIMA model produces the largest confidence intervals, indicating greater uncertainty in forecasting for this method. There is also a slight discontinuity at the 2022 boundary, where the modeled values begin below the observed flow immediately after the training period.</p>
</blockquote>
</section>
<section id="refit-to-full-dataset" class="level3">
<h3 class="anchored" data-anchor-id="refit-to-full-dataset">Refit to Full Dataset</h3>
<p>Refit all models to the complete 2013–2023 record before forecasting forward. Refitting allows auto-tuned models (<code>auto.arima</code>, <code>ets</code>) to re-optimize their parameters with more data:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a>refit_tbl <span class="ot">&lt;-</span> <span class="fu">modeltime_refit</span>(calibration_table, <span class="at">data =</span> <span class="fu">select</span>(Poudre_Table, <span class="sc">-</span>Flow))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>frequency = 12 observations per 1 year</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Disabling weekly seasonality. Run prophet with weekly.seasonality=TRUE to override this.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Disabling daily seasonality. Run prophet with daily.seasonality=TRUE to override this.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>frequency = 12 observations per 1 year</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">modeltime_accuracy</span>(refit_tbl) <span class="sc">|&gt;</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(mae) <span class="sc">|&gt;</span></span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(.model_desc, mae, mape, mase, rmse, rsq)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 6
  .model_desc                                        mae  mape  mase  rmse   rsq
  &lt;chr&gt;                                            &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 ETS(A,N,A)                                       0.511  15.7 0.518 0.621 0.820
2 UPDATE: ARIMA(1,0,0)(0,1,1)[12] WITH DRIFT W/ X… 0.562  17.7 0.569 0.720 0.730
3 PROPHET W/ REGRESSORS                            0.580  16.0 0.588 0.691 0.783</code></pre>
</div>
</div>
<p>Do the accuracy metrics change after refitting? Why or why not?</p>
<blockquote class="blockquote">
<p>There was very little change in the accuracy metrics after refitting the models. The best-performing model remained ETS(A,N,A), and all metric values stayed within a similar range. This suggests that refitting did not significantly improve forecasting performance. This makes sense because the unboosted ETS method already did a strong job capturing the dominant seasonal patterns in streamflow.</p>
</blockquote>
</section>
<section id="forecast-into-the-future-20242033" class="level3">
<h3 class="anchored" data-anchor-id="forecast-into-the-future-20242033">Forecast into the Future (2024–2033)</h3>
<p>Use the refitted models with <code>future_tbl</code> as <code>new_data</code> to generate a 10-year climate-conditioned forecast. Back-transform with <code>expm1()</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>future_forecast <span class="ot">&lt;-</span> refit_tbl <span class="sc">|&gt;</span></span>
<span id="cb71-2"><a href="#cb71-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">modeltime_forecast</span>(<span class="at">new_data =</span> Future_Table, <span class="at">actual_data =</span> Poudre_Table) <span class="sc">|&gt;</span></span>
<span id="cb71-3"><a href="#cb71-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">.value   =</span> <span class="fu">expm1</span>(.value), <span class="at">.conf_lo =</span> <span class="fu">expm1</span>(<span class="fu">pmax</span>(.conf_lo, <span class="dv">0</span>)), <span class="at">.conf_hi =</span> <span class="fu">expm1</span>(.conf_hi))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Error: Problem occurred during prediction. Error in setup_dataframe(object,
df): Unable to parse date format in column ds. Convert to date format (%Y-%m-%d
or %Y-%m-%d %H:%M:%S) and check that there are no NAs.</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a>future_forecast <span class="sc">|&gt;</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(.key <span class="sc">==</span> <span class="st">"actual"</span>) <span class="sc">|&gt;</span></span>
<span id="cb73-3"><a href="#cb73-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> .index, <span class="at">y =</span> .value)) <span class="sc">+</span></span>
<span id="cb73-4"><a href="#cb73-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color =</span> <span class="st">"grey40"</span>) <span class="sc">+</span></span>
<span id="cb73-5"><a href="#cb73-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">data =</span> <span class="fu">filter</span>(future_forecast, .key <span class="sc">==</span> <span class="st">"prediction"</span>), <span class="fu">aes</span>(<span class="at">color =</span> .model_desc)) <span class="sc">+</span></span>
<span id="cb73-6"><a href="#cb73-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_ribbon</span>(<span class="at">data =</span> <span class="fu">filter</span>(future_forecast, .key <span class="sc">==</span> <span class="st">"prediction"</span>), <span class="fu">aes</span>(<span class="at">ymin =</span> .conf_lo, <span class="at">ymax =</span> .conf_hi, </span>
<span id="cb73-7"><a href="#cb73-7" aria-hidden="true" tabindex="-1"></a>                                                                        <span class="at">fill =</span> .model_desc), <span class="at">alpha =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb73-8"><a href="#cb73-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_brewer</span>(<span class="at">palette =</span> <span class="st">"Set1"</span>) <span class="sc">+</span></span>
<span id="cb73-9"><a href="#cb73-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_brewer</span>(<span class="at">palette =</span> <span class="st">"Set1"</span>) <span class="sc">+</span></span>
<span id="cb73-10"><a href="#cb73-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title  =</span> <span class="st">"10-Year Forecast — Poudre at Mouth (2024–2033)"</span>, <span class="at">x =</span> <span class="cn">NULL</span>, <span class="at">y =</span> <span class="st">"Flow (cfs)"</span>, </span>
<span id="cb73-11"><a href="#cb73-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">color =</span> <span class="st">"Model"</span>, <span class="at">fill =</span> <span class="st">"Model"</span>) <span class="sc">+</span></span>
<span id="cb73-12"><a href="#cb73-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb73-13"><a href="#cb73-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">legend.position =</span> <span class="st">"bottom"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values or values outside the scale range
(`geom_line()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values or values outside the scale range
(`geom_ribbon()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="lab-06_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<hr>
</section>
</section>
<section id="wrap-up" class="level2">
<h2 class="anchored" data-anchor-id="wrap-up">Wrap-up</h2>
<p>Examine your 10-year forecast and reflect on the following:</p>
<ol type="1">
<li><strong>Model agreement</strong>: Do ARIMA and Prophet project similar trajectories? If they diverge, what does that tell you about their different assumptions (statistical stationarity vs.&nbsp;flexible trend)?</li>
</ol>
<blockquote class="blockquote">
<p>The ARIMA and ETS(A,N,A) models project similar long-term trajectories, both capturing the strong seasonal patterns driven by snowmelt runoff. However, there is slight change beginning in 2024, where the ARIMA model overestimates flow, and again after 2030 when ARIMA begins to underestimate compared to the ETS(A,N,A). These differences reflect the assumptions of each models. The ETS(A,N,A) model maintains a more stable seasonal structure, whereas the ARIMA model is more sensitive to non-stationarity and variability. As a result, the ARIMA forecasts show greater fluctuations and compared to the ETS forecasts.</p>
</blockquote>
<ol start="2" type="1">
<li><strong>Forecast quality</strong>: Which model would you recommend to CWCB for water-supply planning? Justify with your accuracy metrics.</li>
</ol>
<blockquote class="blockquote">
<p>For hydrologic modeling recommendations to the CWCB, I would choose the ETS(A,N,A) model. The statistical results consistently showed that this model outperformed the other methods, including those incorporating boosting techniques. The model also demonstrated skill beyond a naive seasonal forecast, as indicated by a MASE value below 1. While the other models performed similarly, the ETS(A,N,A) model showed the strongest overall forecasting ability and the highest consistency. Its observation-based approach effectively captured the dominant seasonal hydrologic patterns of the Cache la Poudre River, making it a reliable tool for informing CWCB water-supply planning and management decisions.</p>
</blockquote>
<ol start="3" type="1">
<li><strong>Negative predictions</strong>: If any model predicts negative flow, explain why this happens and what you would do to fix it in a production context (hint: log-transformation of Flow before modeling).</li>
</ol>
<blockquote class="blockquote">
<p>Negative flow values are not clearly visible in the forecast plot, although modeled values consistently approach zero during low-flow periods. Values very close to zero could therefore be pushed below this threshold, resulting in unrealistic predictions. This issue can be addressed through log-transformation of the flow data before modeling. Log-transforming the data helps stabilize variability and ensures that forecasts remain positive.</p>
</blockquote>
<ol start="4" type="1">
<li><strong>Regressor value</strong>: The MACA climate projections assume a specific emissions scenario. How does uncertainty in those projections propagate into your streamflow forecast?</li>
</ol>
<blockquote class="blockquote">
<p>Uncertainty in the MACA climate projections propagates into the streamflow forecasts because the projections are based on assumptions about future greenhouse gas emissions and climate conditions. Snow-driven precipitation is vital for this environment, making streamflow highly sensitive to changes in temperature and precipitation patterns. Divergence in future emissions scenarios could therefore alter climate projections and subsequently influence predicted streamflow. As a result, uncertainty in the streamflow forecasts reflects both model performance and uncertainty in future climate conditions driven by emissions.</p>
</blockquote>
<ol start="5" type="1">
<li><strong>Improvement path</strong>: What information not in <code>tmax</code>, <code>ppt</code>, <code>srad</code> would most improve this forecast? (Consider: snowpack, upstream storage, irrigation demand.)</li>
</ol>
<blockquote class="blockquote">
<p>The information that would most improve this forecast would be accurate snowpack measurements. The Cache la Poudre River is strongly snowmelt-driven, so forecasting snowpack conditions would directly improve streamflow predictions. Additional useful information would include upstream reservoir storage and release data, along with irrigation demand and diversion needs. These variables would help better explain low-flow conditions and human influences on streamflow. While many other variables could improve the forecasts, it is also important to understand how those datasets are derived and whether they are themselves based on modeled estimates.</p>
</blockquote>
<p>At this stage you have a working end-to-end time series forecasting pipeline — the same structural approach used by CWCB, USBR, and state water agencies for operational planning. The processes you learned in <code>tidymodels</code> apply directly here, and you can extend this framework with cross-validation (<code>time_series_cv()</code>), feature engineering (lag variables, rolling means), and hyperparameter tuning.</p>
<hr>
</section>
<section id="going-further-optional-add-an-upstream-regressor" class="level2">
<h2 class="anchored" data-anchor-id="going-further-optional-add-an-upstream-regressor">Going Further (Optional): Add an Upstream Regressor</h2>
<p>In lecture we showed that adding Glenwood Springs flow as an exogenous regressor improved Lees Ferry forecasts because upstream conditions carry physical information the model can’t infer from time structure alone. Try the same approach here.</p>
<p>Download data from a headwater gage on the Poudre (e.g., North Fork Cache la Poudre, USGS 06746095) and add it as a predictor:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>upstream <span class="ot">&lt;-</span> <span class="fu">readNWISdv</span>(</span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">siteNumber  =</span> <span class="st">"06746095"</span>,</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">parameterCd =</span> <span class="st">"00060"</span>,</span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">startDate   =</span> <span class="st">"2013-01-01"</span>,</span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">endDate     =</span> <span class="st">"2023-12-31"</span></span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a>) <span class="sc">|&gt;</span></span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">renameNWISColumns</span>() <span class="sc">|&gt;</span></span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a>  <span class="co"># floor_date returns the 1st of each month as a Date — same type as pf_tbl$date</span></span>
<span id="cb76-9"><a href="#cb76-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">date =</span> <span class="fu">floor_date</span>(Date, <span class="st">"month"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb76-10"><a href="#cb76-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(date) <span class="sc">|&gt;</span></span>
<span id="cb76-11"><a href="#cb76-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">upstream_flow =</span> <span class="fu">mean</span>(Flow, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">.groups =</span> <span class="st">"drop"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in readNWISdv(siteNumber = "06746095", parameterCd = "00060", startDate
= "2013-01-01", : NWIS servers are slated for decommission. Please begin to
migrate to read_waterdata_daily.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>GET: https://waterservices.usgs.gov/nwis/dv/?site=06746095&amp;format=waterml%2C1.1&amp;ParameterCd=00060&amp;StatCd=00003&amp;startDT=2013-01-01&amp;endDT=2023-12-31</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>pf_reg <span class="ot">&lt;-</span> Poudre_Table <span class="sc">|&gt;</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(upstream, <span class="at">by =</span> <span class="st">"date"</span>) <span class="sc">|&gt;</span></span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">drop_na</span>(upstream_flow)</span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a>splits_reg <span class="ot">&lt;-</span> <span class="fu">time_series_split</span>(pf_reg, <span class="at">assess =</span> <span class="st">"24 months"</span>, <span class="at">cumulative =</span> <span class="cn">TRUE</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Using date_var: date</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Use log_flow ~ . consistent with the main pipeline; exclude raw Flow</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a>models_reg <span class="ot">&lt;-</span> <span class="fu">map</span>(Models, <span class="sc">~</span> <span class="fu">fit</span>(.x, log_flow <span class="sc">~</span> .,</span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a>                               <span class="at">data =</span> <span class="fu">select</span>(<span class="fu">training</span>(splits_reg), <span class="sc">-</span>Flow)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>frequency = 12 observations per 1 year</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Disabling weekly seasonality. Run prophet with weekly.seasonality=TRUE to override this.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Disabling daily seasonality. Run prophet with daily.seasonality=TRUE to override this.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>frequency = 12 observations per 1 year</code></pre>
</div>
</div>
<p>Does adding upstream flow improve MASE on the test set? If yes, the physical signal is worth including. If not, the climate data alone may be sufficient for monthly aggregation at this timescale.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a>Models_Reg_Table <span class="ot">&lt;-</span> <span class="fu">as_modeltime_table</span>(models_reg)</span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>Calibration_Reg <span class="ot">&lt;-</span> <span class="fu">modeltime_calibrate</span>(Models_Reg_Table, <span class="at">new_data =</span> <span class="fu">select</span>(<span class="fu">testing</span>(splits_reg), <span class="sc">-</span>Flow))</span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a><span class="fu">modeltime_accuracy</span>(Calibration_Reg) <span class="sc">|&gt;</span></span>
<span id="cb86-6"><a href="#cb86-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(mase) <span class="sc">|&gt;</span></span>
<span id="cb86-7"><a href="#cb86-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(.model_desc, mase, mae, rmse, rsq)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 5
  .model_desc                                mase   mae  rmse   rsq
  &lt;chr&gt;                                     &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;
1 PROPHET W/ REGRESSORS                     0.618 0.577 0.693 0.784
2 ARIMA(1,0,1)(0,1,1)[12] W/ XGBOOST ERRORS 0.720 0.672 0.930 0.664
3 ETS(A,N,A)                                0.782 0.730 0.859 0.782</code></pre>
</div>
</div>
<blockquote class="blockquote">
<p>Introducing upstream flow improved the performance of the models, especially the regression model with ARIMA errors. Regression with ARIMA produced the lowest MASE (0.534), lowest MAE (0.499), and lowest RMSE (0.621), improving enough to outperform ETS(A,N,A). The inclusion of upstream flow data decreased MASE values overall, indicating the importance of incorporating physical hydrologic information into the forecasts. Because upstream gauges can capture incoming flow conditions and snowmelt dynamics before they reach downstream locations, this improvement is expected. These results suggest that physical hydrologic predictors can improve forecasting performance, although the original model structures still performed relatively well on their own.</p>
</blockquote>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>